MatchId = model.MatchId,
Name = model.Name,
MatchDateTimeStart = model.MatchDateTimeStart,
MatchDateTimeEnd = model.MatchDateTimeEnd,
PlaceId = model.Place.PlaceId,
AssociationId = model.Association.AssociationId,
PlaceId = model.Place.PlaceId,
OpenMatch = model.OpenMatch,
UnifyClassifications = model.UnifyClassifications