name: Web API

on:
  push:
    branches: [ main ]
    paths:
    - "SemperPrecisStageTracker.API/**"
    - "SemperPrecisStageTracker.Contracts/**"
    - "SemperPrecisStageTracker.Domain/**"
    - "SemperPrecisStageTracker.Mocks/**"
    - "SemperPrecisStageTracker.Models/**"
    - "SemperPrecisStageTracker.EF/**"
    - "SemperPrecisStageTracker.Shared/**"
    - "SemperPrecisStageTracker.API.Tests/**"
    - "SemperPrecisStageTracker/.github/workflows/build.yml"
  workflow_dispatch:  

env:
  APP_PATH: ./SemperPrecisStageTracker.API/SemperPrecisStageTracker.API.csproj
  AZURE_WEBAPP_NAME: semperprecisapi    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './myapp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x'           # set this to the dot net version to use

jobs:
  build_and_deploy:
    name: Build and deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ${{ env.APP_PATH }}

    - name: Build
      run: dotnet build ${{ env.APP_PATH }} --configuration Release --no-restore
    
    - name: dotnet test
      run: dotnet test ./SemperPrecisStageTracker.API.Tests/SemperPrecisStageTracker.API.Tests.csproj --logger trx --results-directory "TestResults"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: TestResults
      if: ${{ always() }}

    - name: dotnet publish
      run: dotnet publish ${{ env.APP_PATH }} -c Release --no-build --no-restore -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
   
    - uses: azure/login@v1
      name: 'Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.API_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
  ef_migrations:
    name: EF migrations
    needs: build_and_deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install EF tools
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore

    - name: Install dependencies
      run: dotnet restore ${{ env.APP_PATH }}
    
    - uses: azure/login@v1
      name: 'Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: Azure/get-keyvault-secrets@v1
      name: 'KVConnection'
      with:
        keyvault: "semperprecisKV" # name of key vault in Azure portal
        secrets: 'GHConnectionString'  # comma separated list of secret keys to fetch from key vault 
      id: KVoutput # ID for secrets that you will reference

    - name: Update database
      run: |
        cd ./SemperPrecisStageTracker.EF
        dotnet ef database update --startup-project ../SemperPrecisStageTracker.API
      env:
        ASPNETCORE_ENVIRONMENT: Development
        connectionStrings__SqlDb: ${{ steps.KVoutput.outputs.GHConnectionString }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
