name: Web API

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

env:
  AZURE_WEBAPP_NAME: semperprecisapi    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './myapp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x'           # set this to the dot net version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore ./SemperPrecisStageTracker.API/SemperPrecisStageTracker.API.csproj
    - name: Build
      run: dotnet build ./SemperPrecisStageTracker.API/SemperPrecisStageTracker.API.csproj --configuration Release --no-restore
      
    - name: dotnet build and publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
      
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.API_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
