name: Frontend

on:
  push:
    branches: [ main ]
    paths:
    - "SemperPrecisStageTracker.Blazor.FrontEnd/**"
    - "SemperPrecisStageTracker.Blazor.Components/**"
    - "SemperPrecisStageTracker.Contracts/**"
    - "SemperPrecisStageTracker.Shared/**"
    - "SemperPrecisStageTracker/.github/workflows/fe.yml"
  workflow_dispatch:  

env:
  APP_PATH: ./SemperPrecisStageTracker.Blazor/SemperPrecisStageTracker.Blazor.csproj
  AZURE_WEBAPP_NAME: semperprecisstagetracker    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './myapp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.x'           # set this to the dot net version to use


jobs:
  build_and_publish:
    name: Build and publish
    environment: production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
   

    - name: Install dependencies
      run: dotnet restore ${{ env.APP_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.APP_PATH }} --configuration Release --no-restore
    
    - name: dotnet build and publish
      run: dotnet publish ${{ env.APP_PATH }} -c Release --no-restore --no-build -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
      # run: dotnet publish ${{ env.APP_PATH }} -c Release --no-restore --no-build -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
    
    - uses: azure/login@v1
      name: 'Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.FE_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear